name: Phizik
favicon: null
layout_spectrum: 0.9526016756426543
typography_spectrum: 0.8916135844774544
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5009498349390924
  lightness: 0.0356887758243829
  saturation: 0.029860106064006686
  rhythmicContrast: 0.3894187258556485
purpose: []
